// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for RestClientSDKLibraryClient.
    /// </summary>
    public static partial class RestClientSDKLibraryClientExtensions
    {
            /// <summary>
            /// Facilitates the game of Tic Tac Toe by accepting a JSON input representing
            /// the human player's move and returning a JSON object with Azure's move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The input payload representing human player's move.
            /// </param>
            public static object ExecuteMoveResponse(this IRestClientSDKLibraryClient operations, ExecuteMove body = default(ExecuteMove))
            {
                return Task.Factory.StartNew(s => ((IRestClientSDKLibraryClient)s).ExecuteMoveResponseAsync(body), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Facilitates the game of Tic Tac Toe by accepting a JSON input representing
            /// the human player's move and returning a JSON object with Azure's move
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The input payload representing human player's move.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ExecuteMoveResponseAsync(this IRestClientSDKLibraryClient operations, ExecuteMove body = default(ExecuteMove), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ExecuteMoveResponseWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
